echo Creating virtual environment...
python -m venv env

echo Activating virtual environment...
call env\Scripts\activate.bat

echo Installing required packages...
pip install -r requirements.txt

echo Starting the application...
python app.py